# Generated by Django 3.1.7 on 2021-03-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0004_auto_20210313_0010'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='bankaccount',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
